// Given a string, WAM to return all its subsequences in an arraylist.
// A string is a subsequence of a given String that it generated by deleting some character of a given string without changing its order.

import java.util.*;

public class SubSequences {

  // Creating a getSubSequence -> It return all its subsequence in an arraylist.
  public static ArrayList<String> getSubSequence(String str) {
    ArrayList<String> ans = new ArrayList<>();
    // Base Case
    if (str.length() == 0) {
      ans.add("");
      return ans;
    }
    // self work
    char curr = str.charAt(0);
    // Recursive work
    ArrayList<String> smallAns = getSubSequence(str.substring(1));
    for (String i : smallAns) {
      ans.add(i);
      ans.add(curr + i);
    }
    return ans;
  }

  // Creating a printSubSequence -> It return the subsequence of the given string without using a Array list.
  public static void printSubSequence(String s, String currAns) {
    // Base Case
    if (s.length() == 0) {
      System.out.print(currAns + " ");
      return;
    }
    char curr = s.charAt(0);
    String remString = s.substring(1);
    // add curr
    printSubSequence(remString, currAns + curr);
    // do not add curr
    printSubSequence(remString, currAns);
  }

  public static void main(String args[]) {
    Scanner sc = new Scanner(System.in);
    System.out.print("Enter the String: ");
    String str = sc.nextLine();
    System.out.println("Printing the Subsequences by using Array list");
    ArrayList<String> ans = getSubSequence(str);
    for (String i : ans) {
      System.out.print(" " + i);
    }
    System.out.println();
    System.out.println(
      "Printing the Subsequences without using the Array List"
    );
    printSubSequence(str, "");
    sc.close();
  }
}
