// Given a string, WAM to return all its subsequences in an arraylist.
// A string is a subsequence of a given String that it generated by deleting some character of a given string without changing its order.

import java.util.*;

public class SubSequences {

  // Creating a getSubSequence -> It return all its subsequence in an arraylist.
  public static ArrayList<String> getSubSequence(String str) {
    ArrayList<String> ans = new ArrayList<>();
    // Base Case
    if (str.length() == 0) {
      ans.add("");
      return ans;
    }
    // self work
    char curr = str.charAt(0);
    // Recursive work
    ArrayList<String> smallAns = getSubSequence(str.substring(1));
    for (String i : smallAns) {
      ans.add(i);
      ans.add(curr + i);
    }
    return ans;
  }

  public static void main(String args[]) {
    Scanner sc = new Scanner(System.in);
    System.out.print("Enter the String: ");
    String str = sc.nextLine();
    System.out.print("Printing all its subsequences: ");
    ArrayList<String> ans = getSubSequence(str);
    for (String i : ans) {
      System.out.print(" " + i);
    }
  }
}
